// Mocks generated by Mockito 5.4.5 from annotations
// in guia_moteis/test/moteis_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:connectivity_plus/connectivity_plus.dart' as _i7;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i8;
import 'package:guia_moteis/data/datasources/local_cache.dart' as _i5;
import 'package:guia_moteis/data/datasources/remote_data_source.dart' as _i3;
import 'package:guia_moteis/data/models/moteis_model.dart' as _i6;
import 'package:guia_moteis/data/services/moteis_api_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMoteisApiService_0 extends _i1.SmartFake
    implements _i2.MoteisApiService {
  _FakeMoteisApiService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataSource extends _i1.Mock implements _i3.RemoteDataSource {
  MockRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MoteisApiService get apiService =>
      (super.noSuchMethod(
            Invocation.getter(#apiService),
            returnValue: _FakeMoteisApiService_0(
              this,
              Invocation.getter(#apiService),
            ),
          )
          as _i2.MoteisApiService);

  @override
  _i4.Future<Map<String, dynamic>> fetchMoteisJson() =>
      (super.noSuchMethod(
            Invocation.method(#fetchMoteisJson, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);
}

/// A class which mocks [LocalCache].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalCache extends _i1.Mock implements _i5.LocalCache {
  MockLocalCache() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> cacheMoteis(_i6.MoteisModel? model) =>
      (super.noSuchMethod(
            Invocation.method(#cacheMoteis, [model]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i6.MoteisModel?> getCachedMoteis() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedMoteis, []),
            returnValue: _i4.Future<_i6.MoteisModel?>.value(),
          )
          as _i4.Future<_i6.MoteisModel?>);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i7.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i8.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onConnectivityChanged),
            returnValue: _i4.Stream<List<_i8.ConnectivityResult>>.empty(),
          )
          as _i4.Stream<List<_i8.ConnectivityResult>>);

  @override
  _i4.Future<List<_i8.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i4.Future<List<_i8.ConnectivityResult>>.value(
              <_i8.ConnectivityResult>[],
            ),
          )
          as _i4.Future<List<_i8.ConnectivityResult>>);
}
